### ISSUE TITLE
Show Extentions Issues 

### ISSUE THREAD

**Issue by megabugman** [tranht17/WinTune#11]
I. Missing ToolTip
Show Extensions ToolTip is missing indicating that a Explorer Restart is needed.

II. CheckBox incorrect
After manually activating or deactivating show extensions via control panel
WinTune "Show Extensions" is not checked/ unchecked correcly
even after restarting WinTune
![disable](https://github.com/tranht17/WinTune/assets/17204819/14fff645-f374-4a3a-a9af-83627d68c805)

III. Deselect All leads to a WinTune Error
To reproduce (do s.th. like)
Check/uncheck Show Extensions, 
Close WinTune
Restart Explorer
-> Deselect All results in an error
![crash2](https://github.com/tranht17/WinTune/assets/17204819/146b730c-16fa-4929-a809-2b706cb3659a)

================= WinTune - Error =================
Time     :20240502004610
OSVersion:10.0.22621
Is64bitOS:1
Func: DisableAutoSuggest
Message  :(2) The system cannot find the file specified.
Stack    :*#1 (1932) : [RegDelete] RegDelete(HKCU2HCU(ItemData.RegKey), ItemData.RegValueName)

**Comment by tranht17** [comment]
@megabugman Thank you for reporting the error.
The above errors have been fixed in v2.3.1

I. This function has been added to automatically refresh and does not require Explorer Restart.
There may be functions that require restarting Explorer, sign out and sign in to the account, or even restarting the computer. To write tooltips or similar for them, I have to retest each function one by one, which is very necessary. takes a lot of time so maybe I'll add more slowly.
II. `After manually activating or deactivating show extensions via control panel` then you can click the `Reload this tab` button to display your correct settings
![2024-05-03_19-56-35](https://github.com/tranht17/WinTune/assets/28561973/826169e3-aae4-49ab-a8a1-41acb04ba59e)
